baseURL = 'https://interactmsz.hu/'
languageCode = 'hu'
defaultContentLanguage = "hu"
title = 'Interact Club Mátészalka'

theme = "newsroom"

canonifyurls = true
pluralizeListTitles = false

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[permalinks]
pages = ':filename/'

[params]
logo = "/logo/interactmsz-logo.svg"
blogDir = "bejegyzések" # edit

color_choice = "FFFFFF"
